// Code generated by skills/sub2api-add-model/scripts/sync_openai_models.py; DO NOT EDIT.
package openai

var SupplementalModels = []Model{
	{ID: "gpt-6-sol", Object: "model", Created: 1790121600, OwnedBy: "openai", Type: "model", DisplayName: "GPT-6 Sol"},
	{ID: "gpt-6-luna", Object: "model", Created: 1790121600, OwnedBy: "openai", Type: "model", DisplayName: "GPT-6 Luna"},
}

var SupplementalModelContexts = map[string]int{
	"gpt-6-sol":  1050000,
	"gpt-6-luna": 1050000,
}
