<template>
  <AppLayout>
    <section class="grid h-[calc(100vh-8rem)] min-h-0 grid-cols-1 gap-4 lg:grid-cols-[320px_minmax(0,1fr)]">
      <aside class="min-h-0 overflow-y-auto rounded-2xl border border-gray-200 bg-white dark:border-dark-700 dark:bg-dark-900">
        <div class="border-b border-gray-200 p-4 dark:border-dark-700"><div class="flex items-center justify-between"><h1 class="font-semibold">{{ t('supportChat.inbox') }}</h1><button class="btn btn-secondary btn-sm" @click="loadConversations">{{ t('common.refresh') }}</button></div><input v-model="search" class="input mt-3 w-full" :placeholder="t('supportChat.searchUser')" /></div>
        <button v-for="conversation in conversations" :key="conversation.id" class="block w-full border-b border-gray-100 px-4 py-3 text-left hover:bg-gray-50 dark:border-dark-800 dark:hover:bg-dark-800" :class="conversation.id === selectedId ? 'bg-primary-50 dark:bg-primary-900/20' : ''" @click="selectConversation(conversation.id)"><div class="flex items-center justify-between gap-2"><span class="truncate text-sm font-medium">{{ conversation.user_username || conversation.user_email || `#${conversation.user_id}` }}</span><span v-if="conversation.unread_by_admin" class="rounded-full bg-red-100 px-2 py-0.5 text-xs text-red-700">{{ conversation.unread_by_admin }}</span></div><span class="text-xs text-gray-500">#{{ conversation.user_id }} · {{ formatTime(conversation.last_message_at || conversation.updated_at) }}</span></button>
        <p v-if="!conversations.length" class="p-6 text-center text-sm text-gray-500">{{ t('supportChat.noConversations') }}</p>
      </aside>
      <div class="flex min-h-0 flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-dark-700 dark:bg-dark-900"><header class="border-b border-gray-200 px-5 py-4 dark:border-dark-700"><h2 class="font-semibold">{{ selected ? (selected.user_username || selected.user_email || `#${selected.user_id}`) : t('supportChat.adminTitle') }}</h2><p class="text-sm text-gray-500">{{ selected ? selected.user_email : t('supportChat.adminDescription') }}</p></header><div ref="pane" class="min-h-0 flex-1 overflow-y-auto bg-gray-50 p-5 dark:bg-dark-950/60"><p v-if="!selected" class="flex h-full items-center justify-center text-sm text-gray-500">{{ t('supportChat.selectConversation') }}</p><div v-else class="space-y-4"><article v-for="message in messages" :key="message.id" class="flex" :class="message.sender_type === 'admin' ? 'justify-end' : 'justify-start'"><div class="max-w-[82%] rounded-2xl px-4 py-3 text-sm" :class="message.sender_type === 'admin' ? 'bg-primary-600 text-white' : 'border border-gray-200 bg-white dark:border-dark-700 dark:bg-dark-800'"><p v-if="message.content" class="whitespace-pre-wrap break-words">{{ message.content }}</p><button v-if="message.attachment" type="button" class="mt-2 flex items-center gap-2 underline" @click="openAttachment(message.attachment)"><span>{{ message.attachment.filename }}</span><span class="text-xs opacity-70">({{ formatBytes(message.attachment.size_bytes) }})</span></button><time class="mt-1 block text-[11px] opacity-70">{{ formatTime(message.created_at) }}</time></div></article></div></div><form v-if="selected" class="border-t border-gray-200 p-4 dark:border-dark-700" @submit.prevent="send"><div class="mb-2 flex flex-wrap gap-1.5"><button v-for="emoji in emojis" :key="emoji" type="button" class="rounded-lg px-2 py-1 text-lg hover:bg-gray-100 dark:hover:bg-dark-800" @click="draft += emoji">{{ emoji }}</button></div><textarea v-model="draft" class="input min-h-20 w-full resize-none" :placeholder="t('supportChat.placeholder')" @keydown.enter.exact.prevent="send" /><div class="mt-2 flex items-center justify-between"><div class="flex items-center gap-2"><input ref="fileInput" type="file" class="hidden" accept="image/gif,image/jpeg,image/png,image/webp,text/plain,application/pdf" @change="pickFile" /><button type="button" class="btn btn-secondary btn-sm" @click="fileInput?.click()"><span>📎</span></button><span v-if="file" class="max-w-48 truncate text-xs text-gray-500">{{ file.name }} <button type="button" class="text-red-500" @click="file = null">×</button></span></div><button class="btn btn-primary" type="submit" :disabled="sending || (!draft.trim() && !file)">{{ t('supportChat.send') }}</button></div><p v-if="error" class="mt-2 text-xs text-red-500">{{ error }}</p></form></div>
    </section>
  </AppLayout>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import AppLayout from '@/components/layout/AppLayout.vue'
import supportChatAPI, { type SupportConversation, type SupportMessage } from '@/api/supportChat'
const { t, locale } = useI18n(); const conversations=ref<SupportConversation[]>([]); const selectedId=ref<number|null>(null); const messages=ref<SupportMessage[]>([]); const draft=ref(''); const file=ref<File|null>(null); const error=ref(''); const search=ref(''); const sending=ref(false); const pane=ref<HTMLElement|null>(null); const fileInput=ref<HTMLInputElement|null>(null); const emojis=['👍','✅','🎉','🙏','😊','🤝','💡','📌','⏳','❤️']; let timer:ReturnType<typeof setInterval>|undefined
const selected=computed(()=>conversations.value.find(v=>v.id===selectedId.value)); const formatTime=(value:string)=>new Intl.DateTimeFormat(locale.value,{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))
const formatBytes=(value:number)=>value<1024*1024?`${Math.ceil(value/1024)} KB`:`${(value/1024/1024).toFixed(1)} MB`
async function openAttachment(attachment: NonNullable<SupportMessage['attachment']>) { const blob = await supportChatAPI.fetchAttachment(attachment.id, true); const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener'); setTimeout(() => URL.revokeObjectURL(url), 60000) }
function pickFile(event:Event){const selected=(event.target as HTMLInputElement).files?.[0];if(!selected)return;if(selected.size>4*1024*1024){error.value=t('supportChat.fileTooLarge');return}file.value=selected;error.value=''}
async function loadConversations(){const page=await supportChatAPI.adminConversations({search:search.value||undefined});conversations.value=page.items;if(selectedId.value&&!conversations.value.some(v=>v.id===selectedId.value))selectedId.value=null}
async function refresh(){await loadConversations();if(selectedId.value){messages.value=(await supportChatAPI.adminMessages(selectedId.value)).items;await supportChatAPI.adminRead(selectedId.value);await nextTick();if(pane.value)pane.value.scrollTop=pane.value.scrollHeight}}
async function selectConversation(id:number){selectedId.value=id;messages.value=(await supportChatAPI.adminMessages(id)).items;await supportChatAPI.adminRead(id);const item=conversations.value.find(v=>v.id===id);if(item)item.unread_by_admin=0;await nextTick();if(pane.value)pane.value.scrollTop=pane.value.scrollHeight}
async function send(){if(!selectedId.value||(!draft.value.trim()&&!file.value)||sending.value)return;sending.value=true;error.value='';try{messages.value.push(await supportChatAPI.adminSend(selectedId.value,draft.value.trim(),file.value||undefined));draft.value='';file.value=null;await nextTick();if(pane.value)pane.value.scrollTop=pane.value.scrollHeight}catch(err:any){error.value=err?.message||t('supportChat.sendFailed')}finally{sending.value=false}}
watch(search,()=>{void loadConversations()});onMounted(async()=>{await loadConversations();timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},15000)});onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>
