#!/usr/bin/env python3
"""Generate additive OpenAI model data. Default: preview; --write: apply; --check: drift gate.

No network, credentials, production writes, or pricing inferred from model names.
The currently supported contract is Responses text/image models with free cache
writes and the application's existing 0.5x Flex policy. Review new contracts first.
"""
import argparse
import datetime
from decimal import Decimal
import json
from pathlib import Path
import re
import subprocess
import sys


def number(value):
    return format(Decimal(str(value)), 'f')


def quoted(value):
    return json.dumps(value, ensure_ascii=False)


def generate(repo, manifest):
    spec = json.loads(manifest.read_text())
    verified = datetime.date.fromisoformat(spec['verified_at'])
    created = int(datetime.datetime.combine(verified, datetime.time(), datetime.timezone.utc).timestamp())
    models = spec['models']
    ids = [m['id'] for m in models]
    if not models or len(set(ids)) != len(ids):
        raise ValueError('model IDs must be nonempty and unique')
    for m in models:
        if not re.fullmatch(r'gpt-[a-z0-9.-]+', m['id']):
            raise ValueError('invalid model ID')
        if m['cache_write_policy'] != 'free' or m['flex_multiplier'] != 0.5:
            raise ValueError('unsupported billing contract: update generator and runtime together')
        if m['reasoning'] != ['none', 'low', 'medium', 'high', 'xhigh', 'max']:
            raise ValueError('unsupported reasoning contract: review runtime capabilities')
        if not m['source'].startswith('https://developers.openai.com/'):
            raise ValueError('official model source required')
        for key in ['context', 'output_limit', 'input_per_million', 'cached_per_million',
                    'output_per_million', 'fast_multiplier', 'long_context_threshold',
                    'long_input_multiplier', 'long_output_multiplier']:
            if not Decimal(str(m[key])).is_finite() or Decimal(str(m[key])) <= 0:
                raise ValueError(f'{key} must be finite and positive')
        for key in ['context', 'output_limit', 'long_context_threshold']:
            if not isinstance(m[key], int):
                raise ValueError(f'{key} must be an integer')

    header = '// Code generated by skills/sub2api-add-model/scripts/sync_openai_models.py; DO NOT EDIT.\n'
    pkg = header + 'package openai\n\nvar SupplementalModels = []Model{\n'
    pkg += ''.join(f'{{ID:{quoted(m["id"])}, Object:"model", Created:{created}, OwnedBy:"openai", Type:"model", DisplayName:{quoted(m["name"])}}} ,\n' for m in models)
    pkg += '}\n\nvar SupplementalModelContexts = map[string]int{\n'
    pkg += ''.join(f'{quoted(m["id"])}:{m["context"]},\n' for m in models) + '}\n'

    service = header + 'package service\n\nvar supplementalPricing = map[string]*LiteLLMModelPricing{\n'
    billing = '\nvar supplementalBillingPricing = map[string]*ModelPricing{\n'
    frontend = header + 'export const supplementalOpenAIModels = ' + json.dumps([
        {'id': m['id'], 'name': m['name'], 'context': m['context'], 'output': m['output_limit'], 'reasoning': m['reasoning']}
        for m in models], ensure_ascii=False, indent=2) + '\n'
    resource_path = repo / 'backend/resources/model-pricing/model_prices_and_context_window.json'
    raw = resource_path.read_text()
    resource = json.loads(raw)
    updates = {}
    field_pairs = [
        ('input_per_million', 'InputCostPerToken', 'InputPricePerToken', 'input_cost_per_token'),
        ('cached_per_million', 'CacheReadInputTokenCost', 'CacheReadPricePerToken', 'cache_read_input_token_cost'),
        ('output_per_million', 'OutputCostPerToken', 'OutputPricePerToken', 'output_cost_per_token'),
    ]
    for m in models:
        ident = quoted(m['id'])
        service += ident + ':{\n'
        billing += ident + ':{\n'
        entry = {'litellm_provider': 'openai', 'mode': 'chat', 'max_input_tokens': m['context'],
                 'max_output_tokens': m['output_limit'], 'max_tokens': m['output_limit'],
                 'supports_reasoning': True, 'supports_vision': True,
                 'supports_function_calling': True, 'supports_prompt_caching': True,
                 'supports_service_tier': True, 'source': m['source'],
                 'cache_creation_input_token_cost': 0,
                 'cache_creation_input_token_cost_priority': 0,
                 'long_context_input_token_threshold': m['long_context_threshold'],
                 'long_context_input_cost_multiplier': m['long_input_multiplier'],
                 'long_context_output_cost_multiplier': m['long_output_multiplier']}
        for source, lite, bill, json_key in field_pairs:
            standard = Decimal(str(m[source])) / 1_000_000
            fast = standard * Decimal(str(m['fast_multiplier']))
            service += f'{lite}:{number(standard)}, {lite}Priority:{number(fast)},\n'
            billing += f'{bill}:{number(standard)}, {bill}Priority:{number(fast)},\n'
            entry[json_key] = float(standard)
            entry[json_key + '_priority'] = float(fast)
        service += f'LongContextInputTokenThreshold:{m["long_context_threshold"]}, LongContextInputCostMultiplier:{m["long_input_multiplier"]}, LongContextOutputCostMultiplier:{m["long_output_multiplier"]},\nLiteLLMProvider:"openai", Mode:"chat", SupportsPromptCaching:true, SupportsServiceTier:true,\n}},\n'
        billing += f'LongContextInputThreshold:{m["long_context_threshold"]}, LongContextInputMultiplier:{m["long_input_multiplier"]}, LongContextOutputMultiplier:{m["long_output_multiplier"]},\nCacheCreationPriceExplicit:true,\n}},\n'
        updates[m['id']] = entry
    service += '}\n' + billing + '}\n'
    # Patch only the selected top-level JSON entries, retaining unrelated bytes.
    for key, entry in updates.items():
        replacement = '  ' + quoted(key) + ': ' + json.dumps(entry, ensure_ascii=False, indent=2).replace('\n', '\n  ')
        pattern = r'^  ' + re.escape(quoted(key)) + r': \{.*?^  \}'
        if key in resource:
            raw, count = re.subn(pattern, lambda _: replacement, raw, count=1, flags=re.M | re.S)
            if count != 1:
                raise ValueError(f'cannot locate JSON entry {key}; no files written')
        else:
            raw = raw.rstrip()[:-1].rstrip() + ',\n' + replacement + '\n}\n'
    parsed = json.loads(raw)
    if any(parsed[k] != v for k, v in resource.items() if k not in updates):
        raise ValueError('unrelated pricing changed')
    outputs = {
        'backend/internal/pkg/openai/supplemental_models_generated.go': pkg,
        'backend/internal/service/supplemental_pricing_generated.go': service,
        'frontend/src/constants/supplementalOpenAIModels.ts': frontend,
        str(resource_path.relative_to(repo)): raw,
    }
    for path in list(outputs):
        if path.endswith('.go'):
            outputs[path] = subprocess.run(['gofmt'], input=outputs[path], text=True, capture_output=True, check=True).stdout
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repo', type=Path, default=Path(__file__).resolve().parents[3])
    parser.add_argument('--manifest', type=Path)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    repo = args.repo.resolve()
    manifest = args.manifest or Path(__file__).with_name('openai-supplemental.json')
    outputs = generate(repo, manifest)
    changed = []
    for relative, content in outputs.items():
        path = repo / relative
        if not path.exists() or path.read_text() != content:
            changed.append(relative)
    for relative in changed:
        print(('WRITE ' if args.write else 'DRIFT ') + relative)
    if args.write:
        for relative in changed:
            path = repo / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(outputs[relative])
    print(f'models={len(json.loads(manifest.read_text())["models"])} changed={len(changed)}')
    return 1 if args.check and changed else 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as exc:
        print(f'ERROR: {exc}', file=sys.stderr)
        sys.exit(2)
