// Code generated by skills/sub2api-add-model/scripts/sync_openai_models.py; DO NOT EDIT.
package service

var supplementalPricing = map[string]*LiteLLMModelPricing{
	"gpt-6-sol": {
		InputCostPerToken: 0.000002, InputCostPerTokenPriority: 0.000004,
		CacheReadInputTokenCost: 0.0000002, CacheReadInputTokenCostPriority: 0.0000004,
		OutputCostPerToken: 0.00001, OutputCostPerTokenPriority: 0.00002,
		LongContextInputTokenThreshold: 272000, LongContextInputCostMultiplier: 2, LongContextOutputCostMultiplier: 1.5,
		LiteLLMProvider: "openai", Mode: "chat", SupportsPromptCaching: true, SupportsServiceTier: true,
	},
	"gpt-6-luna": {
		InputCostPerToken: 0.0000001, InputCostPerTokenPriority: 0.0000002,
		CacheReadInputTokenCost: 0.00000001, CacheReadInputTokenCostPriority: 0.00000002,
		OutputCostPerToken: 0.0000005, OutputCostPerTokenPriority: 0.0000010,
		LongContextInputTokenThreshold: 272000, LongContextInputCostMultiplier: 2, LongContextOutputCostMultiplier: 1.5,
		LiteLLMProvider: "openai", Mode: "chat", SupportsPromptCaching: true, SupportsServiceTier: true,
	},
}

var supplementalBillingPricing = map[string]*ModelPricing{
	"gpt-6-sol": {
		InputPricePerToken: 0.000002, InputPricePerTokenPriority: 0.000004,
		CacheReadPricePerToken: 0.0000002, CacheReadPricePerTokenPriority: 0.0000004,
		OutputPricePerToken: 0.00001, OutputPricePerTokenPriority: 0.00002,
		LongContextInputThreshold: 272000, LongContextInputMultiplier: 2, LongContextOutputMultiplier: 1.5,
		CacheCreationPriceExplicit: true,
	},
	"gpt-6-luna": {
		InputPricePerToken: 0.0000001, InputPricePerTokenPriority: 0.0000002,
		CacheReadPricePerToken: 0.00000001, CacheReadPricePerTokenPriority: 0.00000002,
		OutputPricePerToken: 0.0000005, OutputPricePerTokenPriority: 0.0000010,
		LongContextInputThreshold: 272000, LongContextInputMultiplier: 2, LongContextOutputMultiplier: 1.5,
		CacheCreationPriceExplicit: true,
	},
}
