// Code generated by skills/sub2api-add-model/scripts/sync_openai_models.py; DO NOT EDIT.
export const supplementalOpenAIModels = [
  {
    "id": "gpt-6-sol",
    "name": "GPT-6 Sol",
    "context": 1050000,
    "output": 128000,
    "reasoning": [
      "none",
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  },
  {
    "id": "gpt-6-luna",
    "name": "GPT-6 Luna",
    "context": 1050000,
    "output": 128000,
    "reasoning": [
      "none",
      "low",
      "medium",
      "high",
      "xhigh",
      "max"
    ]
  }
]
