<template>
  <AppLayout>
    <section class="mx-auto flex h-[calc(100vh-8rem)] max-w-5xl flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm dark:border-dark-700 dark:bg-dark-900">
      <header class="flex items-center justify-between gap-3 border-b border-gray-200 px-5 py-4 dark:border-dark-700">
        <div><h1 class="text-lg font-semibold text-gray-900 dark:text-white">{{ t('supportChat.title') }}</h1><p class="text-sm text-gray-500 dark:text-dark-400">{{ t('supportChat.description') }}</p></div>
        <div class="flex items-center gap-2 text-xs"><span class="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2.5 py-1 font-medium text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-200"><span class="h-2 w-2 rounded-full bg-emerald-500" />{{ t('supportChat.connected') }}</span><button class="btn btn-secondary btn-sm" :disabled="loading" @click="load">{{ t('common.refresh') }}</button></div>
      </header>
      <div ref="messagePane" class="min-h-0 flex-1 overflow-y-auto bg-gray-50 p-5 dark:bg-dark-950/60">
        <div v-if="loading && !messages.length" class="flex h-full items-center justify-center text-sm text-gray-500">{{ t('common.loading') }}</div>
        <div v-else-if="!messages.length" class="flex h-full flex-col items-center justify-center text-center text-gray-500 dark:text-dark-400"><div class="mb-3 rounded-2xl bg-primary-50 p-4 text-primary-600 dark:bg-primary-900/20 dark:text-primary-300"><Icon name="chat" size="lg" /></div><p class="font-medium text-gray-700 dark:text-dark-200">{{ t('supportChat.emptyTitle') }}</p><p class="mt-1 text-sm">{{ t('supportChat.emptyDescription') }}</p></div>
        <div v-else class="space-y-4"><article v-for="message in messages" :key="message.id" class="flex" :class="message.sender_type === 'user' ? 'justify-end' : 'justify-start'"><div class="max-w-[82%] rounded-2xl px-4 py-3 text-sm shadow-sm" :class="message.sender_type === 'user' ? 'bg-primary-600 text-white' : 'border border-gray-200 bg-white text-gray-800 dark:border-dark-700 dark:bg-dark-800 dark:text-dark-100'"><p v-if="message.content" class="whitespace-pre-wrap break-words">{{ message.content }}</p><a v-if="message.attachment" :href="supportChatAPI.attachmentUrl(message.attachment.id)" target="_blank" rel="noopener" class="mt-2 flex items-center gap-2 underline"><Icon name="document" size="sm" />{{ message.attachment.filename }} <span class="text-xs opacity-70">({{ formatBytes(message.attachment.size_bytes) }})</span></a><time class="mt-1 block text-[11px] opacity-70">{{ formatTime(message.created_at) }}</time></div></article></div>
      </div>
      <form class="border-t border-gray-200 bg-white p-3 dark:border-dark-700 dark:bg-dark-900 sm:p-4" @submit.prevent="send"><div class="mb-2 flex flex-wrap items-center gap-1.5"><button v-for="emoji in emojis" :key="emoji" type="button" class="rounded-lg px-2 py-1 text-lg hover:bg-gray-100 dark:hover:bg-dark-800" :aria-label="t('supportChat.insertEmoji')" @click="draft += emoji">{{ emoji }}</button></div><label for="support-message" class="sr-only">{{ t('supportChat.messageLabel') }}</label><textarea id="support-message" v-model="draft" :maxlength="10000" :placeholder="t('supportChat.placeholder')" :disabled="sending" class="min-h-20 w-full resize-none rounded-xl border border-gray-200 bg-gray-50 px-3 py-3 text-sm outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20 dark:border-dark-700 dark:bg-dark-800" @keydown.enter.exact.prevent="send" /><div class="mt-2 flex items-center justify-between gap-3"><div class="flex min-w-0 items-center gap-2"><input ref="fileInput" type="file" class="hidden" accept="image/gif,image/jpeg,image/png,image/webp,text/plain,application/pdf" @change="pickFile" /><button type="button" class="btn btn-secondary btn-sm" :aria-label="t('supportChat.attachFile')" @click="fileInput?.click()"><Icon name="upload" size="sm" /></button><span v-if="file" class="max-w-48 truncate text-xs text-gray-500">{{ file.name }} <button type="button" class="text-red-500" @click="file = null">×</button></span></div><div class="flex items-center gap-3"><span class="text-xs text-gray-400">{{ draft.length }}/10000</span><button class="btn btn-primary" type="submit" :disabled="sending || (!draft.trim() && !file)">{{ sending ? t('common.submitting') : t('supportChat.send') }}</button></div></div><p v-if="error" class="mt-2 text-xs text-red-500">{{ error }}</p></form>
    </section>
  </AppLayout>
</template>

<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { Icon } from '@/components/icons'
import AppLayout from '@/components/layout/AppLayout.vue'
import supportChatAPI, { type SupportMessage } from '@/api/supportChat'

const { t, locale } = useI18n(); const messages = ref<SupportMessage[]>([]); const draft = ref(''); const file = ref<File | null>(null); const error = ref(''); const loading = ref(false); const sending = ref(false); const messagePane = ref<HTMLElement | null>(null); const fileInput = ref<HTMLInputElement | null>(null); const emojis = ['👍','✅','🎉','🙏','😊','🤝','💡','📌','⏳','❤️']; let timer: ReturnType<typeof setInterval> | undefined
const formatTime = (value: string) => new Intl.DateTimeFormat(locale.value, { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value))
const formatBytes = (value: number) => value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`
function pickFile(event: Event) { const selected = (event.target as HTMLInputElement).files?.[0]; if (!selected) return; if (selected.size > 4 * 1024 * 1024) { error.value = t('supportChat.fileTooLarge'); return }; file.value = selected; error.value = '' }
async function scrollBottom() { await nextTick(); if (messagePane.value) messagePane.value.scrollTop = messagePane.value.scrollHeight }
async function load() { loading.value = true; try { const page = await supportChatAPI.messages(); messages.value = page.items; await supportChatAPI.read(); await scrollBottom() } finally { loading.value = false } }
async function send() { const content = draft.value.trim(); if ((!content && !file.value) || sending.value) return; sending.value = true; error.value = ''; try { const message = await supportChatAPI.send(content, file.value || undefined); messages.value = [...messages.value, message]; draft.value = ''; file.value = null; await scrollBottom() } catch (err: any) { error.value = err?.message || t('supportChat.sendFailed') } finally { sending.value = false } }
onMounted(async () => { await load(); timer = setInterval(() => { if (document.visibilityState === 'visible' && !sending.value) void load() }, 15000) })
onBeforeUnmount(() => { if (timer) clearInterval(timer) })
</script>
